spring:
  application:
    name: identity-project
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=identityDB;encrypt=true;trustServerCertificate=true
    username: sa
    password: Password.1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

server:
  port: 5060

